[tool.poetry]
name = "das-atom-db"
version = "0.1.0"
description = ""
authors = ["marcocapozzoli <marcocapozzoli90@gmail.com>"]
readme = "README.md"
packages = [{include = "das_atom_db"}]

[tool.poetry.dependencies]
python = "^3.11"
redis = "^5.0.0"
pymongo = "^4.5.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
flake8 = "^6.1.0"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
